backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: posts
    label: Posts
    folder: src/pages/blog/posts
    create: true
    delete: true
    slug: '{{slug}}'
    fields:
      - { label: Template Key, name: template, widget: hidden, default: post }
      - { name: type, default: post, widget: hidden }
      - { name: author, label: Author, widget: string, default: Maeve Wall }
      - {
          label: Slug,
          name: slug,
          widget: hidden,
          hint: White spaces are not allowed. Please use a "-".,
        }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Featured Post, name: featuredpost, widget: boolean }
      - {
          label: Featured Image,
          name: featuredimage,
          required: false,
          widget: image,
        }
      - { label: Body, name: body, widget: markdown }
      - { label: Tags, name: tags, required: false, widget: list }
  - name: pages
    label: Pages
    files:
      - file: src/pages/about/index.md
        label: About Page
        name: about
        fields:
          - { label: Template, name: template, widget: hidden, default: about }
          - { label: slug, name: slug, widget: hidden, default: about }
          - { label: Type, name: type, widget: hidden, default: page }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
      - file: src/pages/index.md
        label: Home Page
        name: home
        fields:
          - { label: template, name: template, widget: hidden, default: home }
          - { label: slug, name: slug, widget: hidden, default: '' }
          - { label: Type, name: type, widget: hidden, default: page }
          - { label: Title, name: title, widget: string, default: Home }
          - { label: Hero Image, name: featuredimage, widget: image }
          - { label: Heading, name: heading, widget: string }
          - {
              label: Sub-heading,
              name: subheading,
              widget: string,
              required: false,
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  {
                    label: Main Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: Source, name: link, widget: image },
                        { label: Description, name: alt, widget: string },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: markdown },
                ],
            }
          - {
              label: Contact,
              name: contact,
              widget: object,
              fields:
                [
                  { label: Button Text, name: buttontext, widget: string },
                  {
                    label: Social Media,
                    name: socialmedia,
                    widget: list,
                    required: false,
                    fields:
                      [
                        {
                          label: Account,
                          name: account,
                          widget: select,
                          options:
                            [instagram, twitter, facebook, podcast, youtube],
                        },
                        { label: Link, name: link, widget: string },
                        {
                          label: Hover Color,
                          name: color,
                          widget: select,
                          options:
                            ['blue', 'pink', 'red', 'purple', 'lightblue'],
                        },
                      ],
                  },
                ],
            }
          - {
              label: Blurbs,
              name: blurbs,
              widget: list,
              fields:
                [
                  {
                    label: Image,
                    name: image,
                    widget: object,
                    fields:
                      [
                        { label: File, name: src, widget: image },
                        {
                          label: Picture Description,
                          name: alt,
                          widget: string,
                        },
                      ],
                  },
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
      - file: src/pages/take-some-time-off/index.md
        label: Podcast Page
        name: podcast
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: podcast,
            }
          - {
              label: slug,
              name: slug,
              widget: hidden,
              default: take-some-time-off,
            }
          - { label: Type, name: type, widget: hidden, default: page }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Image, name: featuredimage, widget: image }
          - { label: Main, name: main, widget: markdown }
      - file: src/pages/contact/index.md
        label: Contact Page
        name: contact
        fields:
          - {
              label: Template,
              name: template,
              widget: hidden,
              default: contact,
            }
          - { label: slug, name: slug, widget: hidden, default: contact }
          - { label: Type, name: type, widget: hidden, default: page }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: featuredimage, widget: image }
          - { label: Description, name: description, widget: text }
